name: Build Next.js Project

on: [pull_request]

jobs:
  nextjs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - run: pnpm install

      - name: husky install
        run: pnpm husky install

      - run: pnpm lint && pnpm build
